r1=5*10^(-2);
r2=7*10^(-2);
r=(r1+r2)/2;
l=2*%pi*r;
n=400;
i=2;
mu1=2.26*10^(-4);
disp("Part a");
d=r2-r1;
a=%pi*d^2/4;
rm=l/(mu1*a);
disp("the reluctance (in At/Wb) of the cast iron toroid is"); disp(rm);
disp("Part b");
mmf=n*i;
phi=mmf/rm;
disp("the flux (in Wb) set up in the toroidis"); disp(phi);
disp("Part c");
mu=4*%pi*10^(-7);
l1=5*10^(-3);
rm1=l1/(mu*a);
mmf1=phi*rm1;
MMF=mmf+mmf1;
i1=MMF/n;
disp("the new value of current required (in A) is"); disp(i1);