clc
P=5e+5//rated power output in Watts
P1=25e+4// power at half rated torque
f=50//frequency in Hz
If=10//rated firld current in amp
Xs=10//reactance in ohm
p=4//no.of poles
Vl=33e+2//line voltage in volts

Vph=Vl/sqrt(3)//phase voltage in volts
Is=P/(sqrt(3)*Vl*0.8)//Current in amp
theta1=acosd(0.8)
E=Vph-(-%i*Xs*(Is*(%i*sind(theta1)+cosd(theta1))))
y=imag(E)
x=real(E)
Er=sqrt((y^2)+(x^2))
theta2=atand(y/x)
d1=asind(P1*Xs/(3*Vph*(abs(E))))
Is1=(Vph-Er*(cosd(d1)-%i*sind(d1)))/(%i*Xs)
y1=imag(Is1)
x1=real(Is1)
Is1r=sqrt((y1^2)+(x1^2))
theta3=atand(y1/x1)
pf=cosd(theta3)
Is2=P/(Vph*3)
E2=Vph-(%i*Xs*(Is2*(%i*sind(0)+cosd(0))))
If1=abs(E2)*If/E
If1r=abs(If1)
If3=15//field current in amp
E3=If3*(Er)/If//in volts
Is3=sqrt(((E3^2)-(Vph^2))/(Xs^2))
P3=3*Vph*Is3*cosd(0)
Ns=120*f/p//synchronous speed
wm=Ns*2*%pi/f//in rad/sec
T=P3/wm//in Nm
printf('\n\n The Armature Current at half rated torque and rated field current=%0.1f Amp\n\n',Is1)
printf('\n\n The power Factor=%0.1f\n\n',pf)
printf('\n\n The Field Current=%0.1f Amp\n\n',abs(If1))
printf('\n\n The Torque for upf operation for 15 amp field current=%0.1f N-m\n\n',T)
