v=10;
f=60;
r=10;
l1=0.01;
l2=0.05;
disp("Part a");
disp("resistance (in Ω) of the coil for maximum power transfer is"); disp(r);
disp("Part b");
l=l1+l2;
x_c=2*%pi*f*l;
c=1/(2*%pi*f*x_c);
disp("the size of the capacitor (in μF) is"); disp(c*10^6);
disp("Part c");
z1=2*r;
i=v/z1;
p=i^2*r;
disp("power delivered (in W) to the coil is"); disp(p);
disp("Part d");
z=sqrt(z1^2+x_c^2);
i1=v/z;
pr=i1^2*r;
disp("Power dlivered (in W) to the col without the capacitor is"); disp(pr);