disp('Matrix A=')
a=[1 -2;1 3]
disp(a)
disp('Eigen values of A are')
eig=spec(a)
disp(eig)
disp('for lambda=2+i')
i=sqrt(-1)
disp('A-(2+i)I=')
b=a-(2+i)*eye(2,2)
disp(b)
disp('With x2 as free variable, x1=-(1-i)x2')
disp('Hence, eigenvector corresponding to lambda=2+i is:')
disp([i-1;1])
disp('for lambda=2-i, eigenvector is:')
disp([-1-i;1])