clc;
clear all;
format('v',11);
mod_a=sqrt(3^2+2^2);
mod_b=sqrt(15^2+3^2);
angle_a=atand(2/3);
angle_b=atand(3/15);
mod_ans=mod_a*mod_b;
angle_ans=angle_a+angle_b;
disp(angle_ans,"phase angle of ans(in degree)=",mod_ans,"mod of ans=");
