r1=1;
r2=1.2;
r=r1+r2;
v=10;
disp("Part a");
v1=v*r2/r;
disp("the maximum voltage (in V) is"); disp(v);
disp("the minimum voltage (in V) is"); disp(v1);
disp("Part b");
v2=v*(r1/2+r2)/r;
disp("the volatge (in V) is"); disp(v2);