clc;
s = %s;
G = 1/(s*(2*s^4+3*s^3+2*s^2+3*s+2));
den = denom(G);
num = numer(G);
tf = den+num;
disp(tf,"closed loop transfer function characteristic polynomial is");
routh = routh_t(tf);
disp(routh);
printf("since the entire row of s^3 is not zero");
printf("\n putting eps = 0 we get one negative sign in 1st row \n");
printf(" \nhence 2 poles in RHP \n");
