vb=13.2;
vg=14.4;
rb=0.5;
rg=0.1;
i=(vg-vb)/(rb+rg);
vrb=i*rb;
vth=vb+vrb;
rth=rb*rg/(rb+rg);
disp("Part a");
rl1=1;
i1=vth/(rth+rl1);
disp("current (in A) through the load resistor is"); disp(i1);
disp("Part b");
rl2=2;
i2=vth/(rth+rl2);
disp("current (in A) through the load resistor is"); disp(i2);
disp("Part c");
rl3=3;
i3=vth/(rth+rl3);
disp("current (in A) through the load resistor is"); disp(i3);