disp("Part a");
disp("the amplitude of the voltage is 170 V");
disp("Part b");
disp("the peak voltage is 340 V");
disp("Part c");
disp("the angular frequency is 377 rad/s");
w=377;
f=w/(2*%pi);
disp("the frequency (in Hz) is"); disp(f);
t=1/f;
disp("the period (in ms) is"); disp(t*1000);