clc;
clear;
mprintf('MACHINE DESIGN \n Timothy H. Wentzell, P.E. \n EXAMPLE-13.7 Page No.296\n');

hpin=5
e=0.73;
Q=(1-e)*hpin*2544;

mprintf('\n Heat generated by system = %f Btu/hr.',Q);

//Note-There is an error in the answer given in textbook
