clear;
clc;
fmin=0.1; 
fmax=100; 
f=fmin:0.1:fmax;
Hdb=20*log(abs(1+%i*f/10)); 
figure
a=gca();
a.data_bounds=[fmin,-20;fmax,40];
a.log_flags="lnn";
subplot(2,1,1)
plot(f,Hdb);
xtitle('|H(w)|db','w')
subplot(2,1,2)
plot(f,atan(f/10));
xtitle('theta(H(w))','w')
a=gca();
a.data_bounds=[fmin,0;fmax,%pi/2];
a.log_flags="lnn";