clc;
clear;
A=[0 1 0;
   1 0 0;
   0 1 1];
B=[1;1;1];
C=[1 0 0];
D=[1];
K=[C;C*A;C*(A*A)];
disp(K);
disp(rank(K),'rank of K matrix is ');
disp("Since the rank is 2 K matrix can be reduced");
disp("As only  the first 2 rows are linearly independent therefore");
T=[1 0 0;0 1 0];
disp(T,'T =');
disp("In this case Q is");
Q=[1 0;0 1];
disp(Q);
Q_inv=inv(Q);
R=T';
//y_red=T*y;
A_red=T*A*R;
B_red=T*B;
C_red=C*R;
D_red=D;