//Example 1.23
clc
disp("Step 1: Identify topology")
disp("Here output voltage is sampled and fed in shunt with the input siganl such that, I_s-I_f = I_i, hence topology is voltage shunt feedback")
disp("")
disp("Step 2 and Step 3: Find input and output circuit")
disp("To find input circuit, set Vo = 0. This places resistor R across the input. To find output circuit, set V_i = 0. This places resistor R across output. The resultant circuit is shown in fig 1.69")
disp("")
disp("Step 4: Replace transistor with its h-parameter equivalent circuits as shown in fig 1.67")
disp("")
disp("Step 5 : Find open loop transresistance")
disp("R_M = Vo/I_s = R_c*Io/I_s = -R_c*I_c/I_s")
disp("    = R_c * -I_c/I_b * I_b/I_s")
icb=(-100*82)/94
format(6)
disp(icb,"-I_c/I_b = -h_fe*R / R+R_c =")
disp("I_b/I_s = Ro||R / R_s||(R+R_i1)")
ri1=1.1+(101*820*10^-3)
disp(ri1,"R_i1(in k-ohm) = h_ie + (1+h_fe)R_e =")
ibs=(82/83)/(83.92+(82/83))
format(7)
disp(ibs,"Therefore,  I_b/I_s =")
rm=-87.23*12*0.0116
format(7)
disp(rm,"Therefore,  R_M(in k-ohm) = Vo/I_s =")
disp("")
disp("Step 6: Calculate beta")
b=-1/(82*10^3)
format(10)
disp("beta = I_f/Io = V_i-Vo/Vo*R =")
disp(b,"     = -1/R =            because (Vo > V_i)")
disp("")
disp("Step 7: Calculate D, R_Mf, A_vf, R_if, R''_of")
d=1+(-1.22*-12.142*10^-2)
format(6)
disp(d,"D = 1 + beta*R_M =")
rmf=-12.142/1.148
format(6)
disp(rmf,"R_Mf(in k-ohm) = R_M/D =")
avf=-10.57
disp("A_vf = V0/V_s = Vo/I_s*R_s =")
disp(avf,"     = R_Mf/R_s =          because R_Mf = Vo/I_s")
ri=((1*82*83.92)/((82*83.92)+(1*83.92)+(82*1)))
disp(ri,"R_i(in k-ohm) = R_s || R_i1 || R =")
rif=(0.976*10^3)/1.148
format(4)
disp(rif,"R_if(in ohm) = R_i/D =")
disp("Ro = infinity")
disp("Therefore,  R_of = infinity/D = infinity      because h_oe = 0")
ro=(12*82)/(94)
format(7)
disp(ro,"R''_o(in k-ohm) = R || R_c =")
rof=(10.468)/1.148
format(6)
disp(rof,"R''_of(in k-ohm) = R''_o/D =")
