//Example 5_13
clc;clear;
// Given values
rho=1000;// the density of water in kg/m^3
v=100;//Flow rate of water in kg/m^3
z_1=120;// m
h_l=35;// m
n_t=0.8;
g=9.81;// The acceleration due to gravity in m/s^2

// Calculation
m=rho*v;//The mass flow rate of water in kg/s
h_t=z_1-h_l;// m
W_t=(m*g*h_t)/1000;// kW
W_e=(n_t*(W_t/1000));// MW
printf('The electric power generated by the actual unit=%0.1f MW\n',W_e);
