a=3+%i*7;
b=4-%i*5;
c=-6+%i*8;
disp("Part a");
disp("A + B ="); disp(a+b);
disp("Part b");
disp("A - B ="); disp(a-b);
disp("Part c");
disp("B + C =") ; disp(b+c);
disp("Part d");
disp("B - C ="); disp(b-c);