//example 1
//maximum power generation by wind turbine
clear
clc
V=10 //Average velocity of wind in m/s
ke=(V^2/2)/1000 //exegy of the blowing air in kJ/kg
D=12 //diameter of wind turbine in m
d=1.18 //density of air in kg/m^3
M=d*%pi*D^2*V/4 //mass flow rate in kg/s
p=M*ke //maximum power generated by wind turbine in kW
printf("\n Hence, the maximum power generated by wind turbine is = %.1f kW. \n",p);