//page 227
//Example 7.1
clc;
clear;
close;
disp('T is a linear operator on F^2 represented by the matrix:');
A = [0 0;1 0];
disp(A,'A = ');
disp('e1 is a cyclic vector.');
disp('if beta = (a,b)');
disp('then with , g = a+ bx');
disp('beta = g(T)e1');
disp('Cyclic subspace generated by e2 is 1-D space spanned by it.');
//end
