//ex8.8
disp('Part A: Q point: V_GS=-2V I_D=2.5mA. At V_GS=-1V, I_D=3.4mA, At V_GS=-3V, I_D=1.8mA. So peak to peak drain current is the difference of the two drain currents=1.6mA')
disp('Part B: Q point: V_GS=0V I_D=4mA. At V_GS=1V, I_D=5.3mA, At V_GS=-1V, I_D=2.5mA. So peak to peak drain current is the difference of the two drain currents=2.8mA')
disp('Part C: Q point: V_GS=8V I_D=2.5mA. At V_GS=9V, I_D=3.9mA, At V_GS=7V, I_D=1.7mA. So peak to peak drain current is the difference of the two drain currents=2.2mA')

