vm=170;
w=377;
r=33;
disp("Part a");
v=vm/sqrt(2);
disp("the reading (in V) of an AC voltmeter is"); disp(v);
disp("Part b");
im=vm/r;
i=im/sqrt(2);
disp("the reading (in A) of the AC ammeter is"); disp(i);