clc;
//Example 22.16
//page no 317
printf("\n Example 22.16 page no 317\n\n");
//a power plant employs steam to generate power 
//adiabatic conditions
z1=0//steam vertical position at inlet,ft
z2=-20//steam vertical position at outlet,ft
v1=120//steam velocity at inlet,ft/s
v2=330//steam velocity at outlet,ft/s
H1=1505.4//steam enthalpy at inlet 
H2=940//steam enthalpy at outlet
Q=0//for adiabatic conditions
g_c=32.174//grav .acc
//applying energy equation
W_s=-(z2/778) - v2^2/(2*g_c*778) - H2  +z1 + v1^2/(2*g_c*778) + H1//work extracted from system
printf("\n work extracted from the system W_s=%f Btu/lb ",W_s);
m_dot=450000//mass flow rate ,lb/h
W_dot_s=m_dot*W_s//total power generated by the turbine 
printf("\n W_dot_s =%f Btu/h",W_dot_s);//approx calculation in book 
W_hp=W_dot_s*3.927e-4//power generated in horsepower hp
printf("\n power generated W_hp=%f hp",W_hp);//approx calculation in book
