disp('To diagonalize the given matrix A')
a=[3 1;1 3]
disp(a,'A=')
eig=spec(a)
disp('Eigen values of A are:')
disp(eig)
disp('for lambda=4')
disp('A-4I=')
disp(a-4*eye(2,2))
b=a-4*eye(2,2)
disp('To find the eigenvector, form an augmented matrix.')
c=[b [0;0]]
disp('performing row operations')
disp(c)
c(2,:)=c(2,:)+c(1,:)
disp(c)
disp('With x2 as free variable, x1=x2')
disp('Hence a basis for the eigenspace is:')
d=[1;1]
disp(d)
disp('Upon normalizing')
disp(d/(sqrt(2)))
u1=d/(sqrt(2))
disp('for lambda=2')
disp('A-2I=')
b=a-2*eye(2,2)
disp(b)
disp('To find the eigenvector, form an augmented matrix.')
c=[b [0;0]]
disp('performing row operations')
disp(c)
c(2,:)=c(2,:)-c(1,:)
disp(c)
disp('With x2 as free variable, x1=-x2')
disp('Hence a basis for the eigenspace is:')
d=[-1;1]
disp(d)
disp('Upon normalizing')
disp(d/(sqrt(2)))
u2=d/(sqrt(2))
disp('Matrix P=')
p=[u1 u2]
disp(p)
disp('The corresponding matrix D=')
disp([eig(2,1) 0;0 eig(1,1)])