r1=2;
r2=5;
r3=10;
v=25;
disp("Part a");
r=1/(1/r1+1/r2+1/r3);
disp("the total resistance (in Ω) is"); disp(r);
disp("Part b");
i=v/r;
disp("the total current drawn (in A) from the source is"); disp(i);