clear ;
clc;
// Example 7.8
printf('Example 7.8\n\n');
printf('Page No. 214\n\n');

// given
m_s = 5.3;// Factory requirement of process steam in kg/s
Pr_s_1 = 2.5;// Pressure of process steam at bar absolute
E_load_1 = 1.10*10^3;// Electrical load requirement in W
E_load_2 = 1.5*10^3;// Electrical load requirement in W
m_e = 6.0;// Mass flow rate of generated electricity in kg/s
Pr_e = 14;// Pressure of generated electricity at bar absolute
T_heat = 2.790*10^6;// Total heat content in J/kg

//The 14 bar absolute steam would undergo an adiabatic heat drop and the steam will be expanded
h_drop = 306*10^3;// Adiabatic heat drop in J/kg
Pr_2 = 2.5;// Expanded pressure at bar absolute
Ex_stm = 0.11;// Exhaust steam percent
Ef_T = 0.65;// Tubine efficiency
R_h_drop = h_drop * Ef_T;// Real heat drop in J/kg
P_T = m_e * R_h_drop;// Power generated by turbine in W
Ef_G = 0.94;// Generator efficiency
P_G = 1.13*10^6;// Output of generator in W

//(a) Combined heat and power system
Eq_Eva = 8;// Equivalent evaporation of steam per kg coal in kg
C_req = m_e/Eq_Eva;// in kg/s
printf('Coal Required is %.2f kg/s\n',C_req)
printf('If the plant operates on a 140-h week for 50 weeks per annum the coal consumption is 18.9*0^6 kg per year.\nAt an average price of, for example, 35 Pound per tonne, the aanual cost is 660*10^3 Pound.\n\n')

//(b) Coal required for process steam
// for low pressure steam
Eq_Eva_2 = 8.25;// Equivalent evaporation of steam per kg coal in kg
Coal_req = m_s/Eq_Eva_2;// in kg/s
printf('Coal Required is %.3f kg/s\n\n',Coal_req)
printf('Assuming similar operating conditions for the plant the total coal consumption is 16.2*10^6 kg per year,\nand the annual cost is 556*10^6 Pound.\n')

//(c)Electrical Power
printf('The cost of 1.15*10^6 W of electricity for the same period of time is,assuming a cost of 23 Pound per 10^6 Wh,177*10^3Pound.\nThe coal equivalent to generate 1.15*10^6 W of power for the grid would be about 5.0*10^6 kg per year.\n\nThe C.H.P. unit saves a coal equivalent of 2.3*10^6kg per year,\nover the system generating process steam and utilizing grid electricty.\nThe economic savings are 83*1063 Pound per year illustrating the benefits of a C.H.P. syatem in this case.')




