a=7.5;
deg_a=53;
b=3;
deg_b=12;
c=5;
deg_c=-60;
disp("Part a");
disp("in polar form A X B has a magnitude of "); disp(a*b);
disp("with a phase angle (in degrees) of"); disp(deg_a+deg_b);
disp("Part b");
disp("in polar form A ÷ B has a magnitude of"); disp(a/b);
disp("with a phase angle (in degrees) of"); disp(deg_a-deg_b);
disp("Part c");
disp("in polar form A X C has a magnitude of"); disp(a*c);
disp("with a phase angle (in degrees) of"); disp(deg_a+deg_c);
disp("Part d");
disp("in polar form A ÷ C has a magnitude of"); disp(a/c);
disp("with a phase angle (in degrees) of"); disp(deg_a-deg_c);
disp("Part e");
disp("in polar form C ÷ B has a magnitude of"); disp(c/b);
disp("with a phase angle (in degrees) of"); disp(deg_c-deg_b);