clear;
clc;
V_t=72;
I_a=200;
r_a=0.045;
N=2500;
k=(V_t-I_a*r_a)/N;
E_a=k*1000;
L=.007;
Rm=.045;
Rb=0.065;
R=Rm+Rb;
T_a=L/R;
I_mx=230;
I_mn=180;
T_on=-T_a*log(-((V_t-E_a)/R-I_mx)/((I_mn)-(V_t-E_a)/R));
R=Rm;
T_a=L/R;
T_off=-T_a*log(-((-E_a)/R-I_mn)/((I_mx)-(-E_a)/R));
T=T_on+T_off;
f=1/T;    printf("chopping freq=%.1f Hz",f);
a=T_on/T;    printf("\nduty cycle ratio=%.3f",a);
