//Example 5.10
clc
disp("Fig. 5.23 shows the implementation of function with 4 to 1 multiplexer. Two of the variables, B and C, are applied to the selection lines. B is connected to S1 and C is connected to S0. The inputs for multiplexer are derived from the implementation table.")
disp("Truth table")
disp("Minterm    A  B  C    F")
disp("   0       0  0  0    0")
disp("   1       0  0  1    1")
disp("   2       0  1  0    0")
disp("   3       0  1  1    1")
disp("   4       1  0  0    0")
disp("   5       1  0  1    1")
disp("   6       1  1  0    1")
disp("   7       1  1  1    0")
disp("")
disp("Implementation table")
disp("     D0  D1  D2  D3")
disp("A''   0   1   2   3   Row 1")
disp("A    4   5   6   7   Row 2")
disp("     0   1   A   A''")
disp("")
disp("As shown in fig. 5.23(c) the implementation table is nothing but the list of the inputs of the miltiplexers and under them list of all the minterms in two rows. The first row lists all those minterms where A is complemented, and the second row lists all the minterms with A uncomplemented. The minterms given in the function are circled and then each column is inserted separately as follows.")
disp("1. If the two minterms in a column are not circled, O is applied to the corresponding multiplexer input (see column 1).")
disp("2. If the two minterms in a column are circled, 1 is applied to the corresponding multiplexer input (see column 2).")
disp("3. If the minterm in the second row is circled and minterms in the first row is not circled, A is applied to the corresponding multiplexer input (see column 3).")
disp("4. If the minterm in the first row is circled and minterm in the second row is not circled, A'' is applied to the corresponding multiplexer input (see column 4).")
