v=120;
r=150;
disp("Part a");
i=v/r;
disp("current flowing through the resistor (in A) is"); disp(i);
disp("Part b");
r1=50;
v1=i*r1;
disp("The new emf required (in V) is"); disp(v1);
disp("Part c");
i2=50*10^(-3);
v2=60;
r2=v2/i2;
disp("the resistance must be increased to a value (in Ω) of"); disp(r2);