clear;
clc;
close;
disp("dy(t)/dt+2y(t)=x(t)");
w=0:0.1:10;
t=w;
dw=.1;
Xw=ones(1,length(w))./(1+%i*w);
Hw=ones(1,length(w))./(2+%i*w);
Yw=Xw.*Hw;
y=Yw*exp(%i*t'*w)*dw*.31;
d=gca()
plot(t,y);
poly1=d.children.children;
poly1.thickness=3;
poly1.foreground=2;
xtitle('y(t)','t')
yy=exp(-t)-exp(-2*t);
disp("y(t)=exp(-t)-exp(-2*t)")
figure
d=gca()
plot(t,yy);
poly1=d.children.children;
poly1.thickness=3;
poly1.foreground=2;
xtitle('y(t)','t')