//ex 6.6.c
clc;
N=100//ASSUMING THE N=100
p=(N)/(2*N)//AS LIMIT N TENDS TO INFINITY HENCE THE EQUATION
disp(p);
disp('AS THE POWER OF THE SIGNAL IS FINITE HENCE THE FOLLOWING SIGNALIS POWER SIGNAL');


