r1=20;
r2=25;
r3=40;
x_l1=50;
x_l2=40;
x_c=40;
z1=r1+%i*x_l1;
z2=r2+%i*x_l2;
z3=r3-%i*x_c;
y1=1/z1;
y2=1/z2;
y3=1/z3;
disp("Part a");
y=y1+y2+y3;
r=1/real(y);
x_l=-1/imag(y);
disp("for an equivalent series circuit the value of resistance (in Ω) is"); disp(r);
disp("and the value of reactance (in Ω) is"); disp(x_l);
disp("Part b");
z=1/y;
r0=real(z);
x_l0=imag(z);
disp("for an equivalent series circuit the value of resistance (in Ω) is"); disp(r0);
disp("and the value of impedance (in Ω) is"); disp(x_l0);