clc;
//Example 33.12
//page no 534
printf("\n Example 33.12 page no 534\n\n")
//estimation of power generated by human heart
P_drop=60//pressure drop in the circulatory system,mmHg
q=0.0033//volumetric flow rate,ft^3/s
hp=(q*P_drop*14.7*(144/760))//power generated 
printf("\npower generated hp=%f hp",hp);//calculation error in book
