clear;
clc;
f=50;
V_s=230;
disp("at no load");
I_m=2;
pf=.3;
I_c=I_m*sind(acosd(pf));
C=I_c/(2*%pi*f*V_s);    printf("value of capacitance=%.3f uF",C*10^6);
disp("at half full load");
I_m=5;
pf=.5;
I_c=I_m*sind(acosd(pf));
C=I_c/(2*%pi*f*V_s);    printf("value of capacitance=%.3f uF",C*10^6);
disp("at full load");
I_m=10;
pf=.7;
I_c=I_m*sind(acosd(pf));
C=I_c/(2*%pi*f*V_s);    printf("value of capacitance=%.3f uF",C*10^6);