v=3.5;
i=15;
disp("Part a");
vp=2*sqrt(2)*v;
disp("the peak-to-peak voltage (in V) across the resistor is"); disp(vp);
disp("Part b");
im=sqrt(2)*i;
disp("the peak current (in mA) throught the resistor is");disp(im);
disp("Part c");
r=v/(i/1000);
disp("the resistance (in Ω) is"); disp(r);