l1=4;
l2=8;
k=0.6;
f=60;
disp("Part a"); 
m=k*sqrt(l1*l2);
x_m=2*%pi*f*m;
x_l1=2*%pi*f*l1;
x_l2=2*%pi*f*l2;
x_l=x_l1+x_l2+x_m;
disp("the total inductive reactance (in kΩ) is");disp(x_l*10^(-3));
disp("Part b");
v=120;
i=v/x_l;
disp("the current (in mA) throught the coil is"); disp(i*10^3);
disp("Part c");
v1=i*(x_l1+x_m);
disp("voltage (in V) across 4 H coil is"); disp(v1);
v2=i*(x_l2+x_m);
disp("voltage (in V) across 8 H coil is");disp(v2);