//ANALOG AND DIGITAL COMMUNICATION
//BY Dr.SANJAY SHARMA
//CHAPTER 3
//RADIO TRANSMITTER
clear all;
clc;
printf("EXAMPLE 3.3(PAGENO 138)");
printf("\n\n\tInput frequency deviation is 10Khz, while the output frequency deviation \nrequired is 60KHz. Thus, a frequency multiplication of 6*3*2 is required.");
printf("\n\n\tThe frequency multiplication of 6 will give the carrier frequency of\n9*6 = 54MHz only. Hence we have to use heterodyning. The two inputs to the \nmixer are the carrier frequency pf 54MHz and oscillator frequency. Assuming \nthat at the output of the mixer addition of imput frequencies is selected the \nrequired oscillator frequency, to have the final carrier output frequency of \n106MHz, comes out to be 52MHz.[52+54 =106]. ");
