i1=10;
i2=0.5;
i3=1.5;
v=120;
disp("Part a");
i=i1+i2+i3;
disp("the total current (in A) supplied by the source is"); disp(i);
disp("Part b");
disp("voltage (in V) across the lamp is"); disp(v);
disp("Part c");
r=v/i;
disp("the combined resistance (in Ω) is");disp(r);
disp("Part d");
i4=15;
r4=v/(i4-i);
disp("the resistance (in Ω) of the fourth load is"); disp(r4);
disp("Part e");
r5=v/i4;
disp("the combined resistance (in Ω) of the four loads is"); disp(r5);