b=0.6;
l=0.02;
disp("Part a");
t1=0.1;
phi=b*l^2;
v1=phi/t1;
disp("the voltage induced (in V) in the wire is"); disp(v1);
disp("Part b");
t2=0.01;
v2=phi/t2;
disp("the voltage induced (n V) in the wire is"); disp(v2);