disp('the augmented matrix is:')
a=[3 -5 0;-2 6 4;1 1 4]
disp(a)
disp('interchange R1 and R3')
a([1,3],:)=a([3,1],:)
disp(a)
disp('R2=R2+2*R1 and R3=R3-3*R1')
a(2,:)=a(2,:)+2*a(1,:)
a(3,:)=a(3,:)-3*a(1,:)
disp(a)
disp('R3=R3+R2')
a(3,:)=a(3,:)+a(2,:)
disp(a)
disp('from the entries of last row, the system is consistent')
disp('hence, u is in the plane spanned by the columns of a')