disp('matrix A corresponding to transformation T is:')
A=[-5 9;4 -7];
disp(A)
disp('determinant of A is:')
disp(det(A))
disp('since det(A) is not equal to zero')
disp('by IMT, A is invertible')
disp('hence, the inverse of A exists')
disp('inverse of A is:')
disp(inv(A))