clear()
//clc()
disp("Example 2 :          Clear the current session window at the press of a key")
printf("\n**********************************************************\n")
disp("Answer  :")
disp("")
disp("Press any key to clear the Session window ")
halt("")
//clc()
