clc
clear

//input
e=235;//e.m.f generated by an armature of a d.c. machine in volts
v=100;//velocity of armature of a d.c. machine in rad/s
i=16;//current in amperes

//calculations
p=e*i;//power of armature in watts
t=p/v;//required torque in newton meter

//output
mprintf('required torque is %3.1f Nm',t)
