deg=41*%pi/180;
v=240;
i=6;
p_out=746;
disp("Part a");
pf=cos(deg);
disp("power factor of the motor is"); disp(pf);
disp("Part b");
s=v*i;
disp("apparent power (in VA) is"); disp(s);
disp("Part c");
p=v*i*pf;
disp("true power (in W) is");disp(p);
disp("Part d");
q=v*i*sin(deg);
disp("reactive power (in VAr) is"); disp(q);
disp("Part d");
eff=p_out*100/p;
disp("the effieciency (in %) of the motor is"); disp(eff);