clear;
clc;
a=30;
R=10;
P=5000;
V_s=sqrt(P*R*2*%pi/(2*3)/(%pi/3+sqrt(3)*cosd(2*a)/2));
V_ph=V_s/sqrt(3);    printf("per phase voltage, V_ph=%.3f V",V_ph);
I_or=sqrt(P*R);
V_s=I_or*%pi/(sqrt(2)*3*cosd(a));
V_ph=V_s/sqrt(3);    
printf("\nfor constant load current");
printf("\nV_ph=%.2f V",V_ph);