clc;
s = %s;
G = syslin('c',100/(s*(s+10)));
H = syslin('c',1/(s+5));
syms t s;
R = laplace(1,t,s);
E = R/(1+G*H);
sse = limit(s*E,s,0);disp(sse,"steady state error for step input:");
R1 = laplace(t,t,s);
E = R1/(1+G*H);
sse = limit(s*E,s,0);disp(sse,"steady state error for ramp input:");