clc;
s=%s;
A = [0 3 1;2 8 1;-10 -5 -2];
B = [10;0;0];
C = [1 0 0];
ss = syslin('c',A,B,C,0);
tf = ss2tf(ss);disp(tf);
H = denom(tf);
routh = routh_t(H);
disp(routh);
printf("one sign change hence one pole in RHP");
