printf("\n trnsfer function of the given network ")
printf("\n Vi(s)=R*I(s)+s*L*I(s)")
printf("\n V0=s*L*I")
printf("\n V0(s)/Vi(s)=s*L*I/(R*I(s)+s*L*I(s))")
printf("V0(s)/Vi(s)=s*L/(R+s*L) is the required transfer function")
