clear;
clc;
V_s=400;
f=50;
I_o=15;
a=45;
I_TA=I_o*120/360;
I_Tr=sqrt(I_o^2*120/360);
I_sr=sqrt(I_o^2*120/180);
V_ml=sqrt(2)*V_s;
V_o=3*V_ml*cosd(a)/%pi;
V_or=V_ml*sqrt((3/(2*%pi))*(%pi/3+sqrt(3/2)*cosd(2*a)));
I_or=I_o;
P_dc=V_o*I_o;
P_ac=V_or*I_or;
RE=P_dc/P_ac;    printf("rectification efficiency=%.5f",RE);
VA=3*V_s/sqrt(3)*I_sr;
TUF=P_dc/VA;    printf("\nTUF=%.4f",TUF);
pf=P_ac/VA;    printf("\ninput pf=%.3f",pf);