//Example_a_9_12 page no:411
clc;
//star delta conversion method
Zrmag=5;
Zrang=0;
Zymag=2;
Zyang=90;
Zbmag=4;
Zbang=-90;
Vrymag=100;
Vryang=0;
Vybmag=100;
Vybang=-120;
Vbrmag=100;
Vbrang=-240;
Zrymag=Zrmag*Zymag;
Zryang=Zrang+Zyang;
Zybmag=Zymag*Zbmag;
Zybang=Zyang+Zbang;
Zbrmag=Zbmag*Zrmag;
Zbrang=Zbang+Zrang;
Zryreal=Zrymag*cosd(Zryang);
Zryimag=Zrymag*sind(Zryang);
Zry=Zryreal+(%i*Zryimag);
Zybreal=Zybmag*cosd(Zybang);
Zybimag=Zybmag*sind(Zybang);
Zyb=Zybreal+(%i*Zybimag);
Zbrreal=Zbrmag*cosd(Zbrang);
Zbrimag=Zbrmag*sind(Zbrang);
Zbr=Zbrreal+(%i*Zbrimag);
Z=Zry+Zyb+Zbr;
Zmag=sqrt(real(Z)^2+imag(Z)^2);
Zang=atand(imag(Z)/real(Z));
Zr_ymag=Zmag/Zbmag;
Zr_yang=Zang-Zbang;
Zy_bmag=Zmag/Zrmag;
Zy_bang=Zang-Zrang;
Zb_rmag=Zmag/Zymag;
Zb_rang=Zang-Zyang;
Irmag=Vrymag/Zr_ymag;
Irang=Vryang-Zr_yang;
Iymag=Vybmag/Zy_bmag;
Iyang=Vybang-Zy_bang;
Ibmag=Vbrmag/Zb_rmag;
Ibang=Vbrang-Zb_rang;
Irreal=Irmag*cosd(Irang);
Irimag=Irmag*sind(Irang);
Ir=Irreal+(%i*Irimag);
Iyreal=Iymag*cosd(Iyang);
Iyimag=Iymag*sind(Iyang);
Iy=Iyreal+(%i*Iyimag);
Ibreal=Ibmag*cosd(Ibang);
Ibimag=Ibmag*sind(Ibang);
Ib=Ibreal+(%i*Ibimag);
I1=Ir-Ib;
I2=Iy-Ir;
I3=Ib-Iy;
I1mag=sqrt(real(I1)^2+imag(I1)^2);
I1ang=atand(imag(I1)/real(I1));
I2mag=sqrt(real(I2)^2+imag(I2)^2);
I2ang=atand(imag(I2)/real(I2));
I2ang=I2ang+180;//converting the angle to positive
I3mag=sqrt(real(I3)^2+imag(I3)^2);
I3ang=atand(imag(I3)/real(I3));
I3ang=I3ang+180;
disp("the line currents are");
disp(I1mag,"the magnitude of current I1 is (in A)");
disp(I1ang,"the angle of current I1 is (in A)");
disp(I2mag,"the magnitude of current I2 is (in A)");
disp(I2ang,"the angle of current I2 is (in A)");
disp(I3mag,"the magnitude of current I3 is (in A)");
disp(I3ang,"the angle of current I3 is (in A)");
Vzrmag=I1mag*Zrmag;
Vzrang=I1ang+Zrang;
Vzymag=I2mag*Zymag;
Vzyang=I2ang+Zyang;
Vzbmag=I3mag*Zbmag;
Vzbang=I3ang+Zbang;
disp("the voltage drop across each star connected load is");//the voltage value varies slightly with text book hence results are rounded off in text book
disp(Vzrmag,"the magnitude of voltage drop across Zr resistor is (in V)");
disp(Vzrang,"the angle of voltage drop across Zr resistor is (in degree)");
disp(Vzymag,"the magnitude of voltage drop across Zy resistor is (in V)");
disp(Vzyang,"the angle of voltage drop across Zy resistor is (in degree)");
disp(Vzbmag,"the magnitude of voltage drop across Zb resistor is (in V)");
disp(Vzbang,"the angle of voltage drop across Zb resistor is (in degree)");
Vromag=100/sqrt(3);
Vroang=-30;
Vyomag=100/sqrt(3);
Vyoang=-150;
Vbomag=100/sqrt(3);
Vboang=-270;
Yrmag=1/Zrmag;
Yrang=0-Zrang;
Yymag=1/Zymag;
Yyang=0-Zyang;
Ybmag=1/Zbmag;
Ybang=0-Zbang;
Yrormag=Vromag*Yrmag;
Yrorang=Vroang+Yrang;
Yyoymag=Vyomag*Yymag;
Yyoyang=Vyoang+Yyang;
Ybobmag=Vbomag*Ybmag;
Ybobang=Vboang+Ybang;
Yrorreal=Yrormag*cosd(Yrorang);
Yrorimag=Yrormag*sind(Yrorang);
Yror=Yrorreal+(%i*Yrorimag);
Yyoyreal=Yyoymag*cosd(Yyoyang);
Yyoyimag=Yyoymag*sind(Yyoyang);
Yyoy=Yyoyreal+(%i*Yyoyimag);
Ybobreal=Ybobmag*cosd(Ybobang);
Ybobimag=Ybobmag*sind(Ybobang);
Ybob=Ybobreal+(%i*Ybobimag);
Y=Yror+Yyoy+Ybob;
Ymag=sqrt(real(Y)^2+imag(Y)^2);
Yang=atand(imag(Y)/real(Y));
Yang=Yang+180;//converting the angle to positive
Yrreal=Yrmag*cosd(Yrang);
Yrimag=Yrmag*sind(Yrang);
Yr=Yrreal+(%i*Yrimag);
Yyreal=Yymag*cosd(Yyang);
Yyimag=Yymag*sind(Yyang);
Yy=Yyreal+(%i*Yyimag);
Ybreal=Ybmag*cosd(Ybang);
Ybimag=Ybmag*sind(Ybang);
Yb=Ybreal+(%i*Ybimag);
Yryb=Yr+Yy+Yb;
Yrybmag=sqrt(real(Yryb)^2+imag(Yryb)^2);
Yrybang=atand(imag(Yryb)/real(Yryb));
Vo_omag=Ymag/Yrybmag;
Vo_oang=Yang-Yrybang;
Vo_oreal=Vo_omag*cosd(Vo_oang);
Vo_oimag=Vo_omag*sind(Vo_oang);
Vo_o=Vo_oreal+(%i*Vo_oimag);
Vroreal=Vromag*cosd(Vroang);
Vroimag=Vromag*sind(Vroang);
Vro=Vroreal+(%i*Vroimag);
Vyoreal=Vyomag*cosd(Vyoang);
Vyoimag=Vyomag*sind(Vyoang);
Vyo=Vyoreal+(%i*Vyoimag);
Vboreal=Vbomag*cosd(Vboang);
Vboimag=Vbomag*sind(Vboang);
Vbo=Vboreal+(%i*Vboimag);
Vro_=Vro-Vo_o;
Vyo_=Vyo-Vo_o;
Vbo_=Vbo-Vo_o;
Vro_mag=sqrt(real(Vro_)^2+imag(Vro_)^2);
Vro_ang=atand(imag(Vro_)/real(Vro_));
Vyo_mag=sqrt(real(Vyo_)^2+imag(Vyo_)^2);
Vyo_ang=atand(imag(Vyo_)/real(Vyo_));
Vbo_mag=sqrt(real(Vbo_)^2+imag(Vbo_)^2);
Vbo_ang=atand(imag(Vbo_)/real(Vbo_));
disp("the displacement neutral voltages are");
disp(Vro_mag,"the magnitude of voltage across Vro is (in V)");
disp(Vro_ang,"the angle of voltage across Vro is (in degree)");
disp(Vyo_mag,"the magnitude of voltage across Vyo is (in V)");
disp(Vyo_ang,"the angle of voltage across Vyo is (in degree)");
disp(Vbo_mag,"the magnitude of voltage across Vbo is (in V)");
disp(Vbo_ang,"the angle of voltage across Vbo is (in degree)");
Ir_mag=Vro_mag/Zrmag;//value of Ir is wrong in text book calculation
Ir_ang=Vro_ang-Zrang;
Iy_mag=Vyo_mag/Zymag;
Iy_ang=Vyo_ang-Zyang;
Iy_ang=Iy_ang+360;//converting to positive angle
Ib_mag=Vbo_mag/Zbmag;
Ib_ang=Vbo_ang-Zbang;
disp("the current in the phases are");
disp(Ir_mag,"the magnitude of current in the R phase is (in A)");
disp(Ir_ang,"the angle of current in the R phase is (in degree)");
disp(Iy_mag,"the magnitude of current in the Y phase is (in A)");
disp(Iy_ang,"the angle of current in the Y phase is (in degree)");
disp(Ib_mag,"the magnitude of current in the B phase is (in A)");
disp(Ib_ang,"the angle of current in the B phase is (in degree)");
//value of Ir is wrong in text book calculation
//the voltages value varies slightly with text book hence results are rounded off in text book
