v1=120;
v2=12.6;
r=10;
disp("Part a");
n=v1/v2;
disp("the turns ratio is"); disp(n);
disp("Part b");
i2=v2/r;
disp("the secondary current (in A) is"); disp(i2);
disp("Part c");
i1=v1/r;
disp("the primary current (in A) is"); disp(i1);