p=250;
t=4*30;
disp("Part a");
e=p*t;
disp("the amount of energ (in kWh) used by the lamp is"); disp(e*10^(-3));
disp("Part b");
rs=5;
cost=rs*e;
disp("the cost (in $) of the energy is"); disp(cost/100);
disp("Part c");
rs1=10;
cost1=rs1*e;
disp("the cost (in $) of the energy is"); disp(cost1/100);