p=60;
v=120;
f=60;
disp("Part a");
r=v^2/p;
disp("the normal hot resistance (in Ω) is"); disp(r);
disp("Part b");
vrms=v/sqrt(2);
disp("the r.m.s. voltage (in V) is"); disp(vrms);
disp("Part c");
v1=85;
r1=r*v1/v;
disp("the resistance (in Ω) of the lamp is"); disp(r1);
disp("Part d");
prms=vrms^2/r1;
disp("the r.m.s. power delivered to the lamp (in W) is"); disp(prms);
disp("Part e");
piv=v*sqrt(2);
disp("the peak inverse voltage (in V) is"); disp(piv);